services:
  2bored2tolerate:
    build: .
    container_name: 2bored2tolerate
    ports:
      - "8080:8080"
      - "25565:25565"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
